### ISSUE TITLE
error: process didn't exit successfully:

### ISSUE THREAD

**Issue by frix0** [MatanHamilis/bitcoin-sighash-steal#2]
What am I doing wrong here? 👶 

cargo run --release -- --address 127.0.0.1:8332 --bitcoin-dir D:\Users\papaz\AppData\Roaming\Bitcoin --log-file D:\Users\papaz\AppData\Roaming\Bitcoin\result2.log --attacker-address 1Priv*********** --steal-txid 16bb6761************************ --steal-vout 1 --vuln-script 47304************************
    Finished release [optimized] target(s) in 0.17s
     Running `target\release\bitcoin-steal-sighash.exe --address 127.0.0.1:8332 --bitcoin-dir D:\Users\papaz\AppData\Roaming\Bitcoin --log-file D:\Users\papaz\AppData\Roaming\Bitcoin\result2.log --attacker-address 1Priv*********** --steal-txid 16bb6761************************ --steal-vout 1 --vuln-script 47304************************`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "Das System kann die angegebene Datei nicht finden." })', src\main.rs:78:50
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
   3: <alloc::string::String as core::fmt::Display>::fmt
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\bitcoin-steal-sighash.exe --address 127.0.0.1:8332 --bitcoin-dir D:\Users\papaz\AppData\Roaming\Bitcoin --log-file D:\Users\papaz\AppData\Roaming\Bitcoin\result2.log --attacker-address 1Priv*********** --steal-txid 16bb6761************************ --steal-vout 1 --vuln-script 47304************************` (exit code: 101)

**Comment by frix0** [comment]
I tried: **set RUST_BACKTRACE=full**

and that's the result

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "Das System kann die angegebene Datei nicht finden." })', src\main.rs:78:50
stack backtrace:
   0:     0x7ff7a24ac4e2 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7a24ac4e2 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7a24ac4e2 - std::sys_common::backtrace::_print_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff7a24ac4e2 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff7a24c4b1b - core::fmt::write
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\fmt\mod.rs:1202
   5:     0x7ff7a24a5f3a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\io\mod.rs:1679
   6:     0x7ff7a24ae544 - std::sys_common::backtrace::_print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff7a24ae544 - std::sys_common::backtrace::print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff7a24ae544 - std::panicking::default_hook::closure$1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:295
   9:     0x7ff7a24ae17a - std::panicking::default_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:314
  10:     0x7ff7a24aed31 - std::panicking::rust_panic_with_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:698
  11:     0x7ff7a24aec3d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:588
  12:     0x7ff7a24acf0f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff7a24ae900 - std::panicking::begin_panic_handler
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
  14:     0x7ff7a24dd175 - core::panicking::panic_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
  15:     0x7ff7a24dd283 - core::result::unwrap_failed
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
  16:     0x7ff7a2415006 - <alloc::string::String as core::fmt::Display>::fmt::h540b1d46c2ce115a
  17:     0x7ff7a23ffe16 - std::sys_common::backtrace::__rust_begin_short_backtrace::h06b7ebee10305407
  18:     0x7ff7a240559c - std::rt::lang_start::{{closure}}::ha2a59c3aef9995b8
  19:     0x7ff7a24a0f2e - core::ops::function::impls::impl$2::call_once
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\ops\function.rs:283
  20:     0x7ff7a24a0f2e - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  21:     0x7ff7a24a0f2e - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  22:     0x7ff7a24a0f2e - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  23:     0x7ff7a24a0f2e - std::rt::lang_start_internal::closure$2
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  24:     0x7ff7a24a0f2e - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  25:     0x7ff7a24a0f2e - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  26:     0x7ff7a24a0f2e - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  27:     0x7ff7a24a0f2e - std::rt::lang_start_internal
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  28:     0x7ff7a24169fc - main
  29:     0x7ff7a24d7f64 - invoke_main
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30:     0x7ff7a24d7f64 - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31:     0x7ffd93b87614 - BaseThreadInitThunk
  32:     0x7ffd941c26a1 - RtlUserThreadStart

**Comment by pbies** [comment]
You are missing .cookie file in Bitcoin Core folder. You need to comment out rpcuser and rpcpassword from bitcoin.conf file and start Bitcoin Core before running the script.
